name: powerpc/sparse

# Controls when the action will run.
on:
  # This allows the build to be triggered manually via the github UI.
  workflow_dispatch:

  push:
    # This triggers the build on a push to any branch named ci/powerpc/<something>
    branches:
    - '**'
    # As long as one of these paths matches
    paths:
      - '!tools/**'		   	# ignore tools
      - '!samples/**'		   	# ignore samples
      - '!Documentation/**'		# ignore Documentation
      - '!arch/**'			# ignore arch changes
      - 'arch/powerpc/**'		# but not arch/powerpc
      - 'arch/Kconfig'			# or common bits in arch
      - '**'				# anything else triggers a build

jobs:
  sparse:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        defconfig: [ppc64, pmac32, mpc885_ads_defconfig]
        image: [fedora-40]
        subarch: [ppc64]
        include:
          - subarch: ppc64le
            defconfig: ppc64le
            image: fedora-40

    env:
      ARCH: powerpc
      TARGET: kernel
      CCACHE: 1
      SPARSE: 2
      SUBARCH: ${{ matrix.subarch }}
      IMAGE: ${{ matrix.image }}
      DEFCONFIG: ${{ matrix.defconfig }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Load ccache
      uses: actions/cache@v4
      with:
        path: ~/.ccache
        key: ${{ matrix.image }}-${{ matrix.subarch }}-${{ matrix.defconfig }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build
      run: |
        mkdir -p ~/.ccache
        ./arch/powerpc/tools/ci-build.sh

    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: sparse-${{ matrix.defconfig }}-${{ matrix.image }}.log
        path: |
          ~/output/sparse.log
